services:
  inclusive-map-db:
    image: "postgis/postgis:17-3.5"
    container_name: "inclusive-map-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: map
    ports:
      - "5437:5432"
    volumes:
      - ./ifc_volume_mount:/var/lib/postgresql/data
